### ISSUE TITLE
能否出个aes_256的查表版本

### ISSUE THREAD

**Issue by BillyWei01** [openluopworld/aes_128#3]
大神你好，我运行了一下您的ace_128查表版本，和jdk自带的实现对比了一下，确实效率很高。
想问下能否出个aes_256的查表版本？
aes_128加密强度已经足够，但如果同时有个aes_256的话会更完备一些。

**Comment by openluopworld** [comment]
您好，我认为需要先明确Jdk里crypto的实现方式，看是由于查表带来的提升，还是jni和java的差异导致的。

这个本身是业余项目，目前没有计划做AES-256和AES-192的。但是开源一般都会有不同密钥强度的实现，可以参考。
https://github.com/openssl/openssl/blob/master/crypto/aes/aes_core.c
https://github.com/ARMmbed/mbedtls/blob/development/library/aes.c

**Comment by BillyWei01** [comment]
我也有过是否是jni和java差异的疑虑，但是测了下连续执行很多次，最终稳定下来后确实是此版本快许多。
如果只是jni和java的差异，在warming之后JIT应该会编译热点代码从而尽量接近native的执行效率。所以应该是算法方面的差异。
Thanks Any Way.
