### ISSUE TITLE
感谢您惊人的代码, 但是还得教您关于您在GitHub上AES的一段代码问题

### ISSUE THREAD

**Issue by rpodman** [openluopworld/aes_128#4]
**尊敬的luopeng先生您好:
                  我在看您关于AES代码实现中的9轮加密中的列混合无论如何都看不懂, 也就是如下代码, 您实现的方式是异常巧妙地, 可是我即使知道结果是对的, 但无法知道为什么您这么做, 可否得到您的回复, 如果您愿意分享的话, 将万分感谢, 谢谢您的代码, 让我懂得了很多.
![image](https://user-images.githubusercontent.com/112320110/187070118-05e41b3d-d6c3-432b-8c3a-0aded2def0e9.png)**

**Comment by openluopworld** [comment]
以第一行的第一个元素为例，最终的结果应该是 `2s0 ^ 3s1 ^ s2 ^ s3`。推导如下：

```c
2s0 ^ 3s1 ^ s2 ^ s3
= 2s0 ^ (2^1)s1 ^ s2 ^ s3
= 2s0 ^ (2s1 ^ s1) ^ s2 ^ s3
= 2s0 ^ 2s1 ^ s1 ^ s2 ^ s3
= (2s0 ^ s0 ^ s0) ^ 2s1 ^ s1 ^ s2 ^ s3
= 2s0 ^ s0 ^ s0 ^ 2s1 ^ s1 ^ s2 ^ s3
= 2s0 ^ 2s1 ^ s0 ^ s0 ^ s1 ^ s2 ^ s3
= 2(s0^s1) ^ s0 ^ (s0 ^ s1 ^ s2 ^ s3)
```

`2(s0^s1)` 表示为 `mult2(tmp ^ tmp[i+1])`
`^ s0` 表示为 `^ tmp[i]`
`^ (s0 ^ s1 ^ s2 ^ s3)` 表示为 `^ t`，其中`t`是`tmp[i] ^ tmp[i+1] ^ tmp[i+2] ^ tmp[i+3]`

其它可以类似推导。

**Comment by rpodman** [comment]
> 

666666666666, 感谢您解答了我的疑惑, 懂了, 再次祝您工作顺利, 万事如意, 感谢您!!!!
