### ISSUE TITLE
再次感谢您惊人的代码, 巧妙地实现方式, 但是还有个解密的问题(逆列混合运算)

### ISSUE THREAD

**Issue by rpodman** [openluopworld/aes_128#5]
尊敬的luopeng先生:
                                 您好, 又是我, 感谢您上次的耐心教导, 让我明白了为什么化简为这个样子, 但是我再看您关于解密的代码时, 有三个变量u v t, 并且用这三个变量计算出接近明文的过程让我又再度产生和之前一样的疑惑, 所以还得向您请教, 希望得到您的再次回复, 再次感谢您, 祝愿您工作顺利, 生活美满, 完事如意.
![image](https://user-images.githubusercontent.com/112320110/188266862-15666884-ca17-4880-9fb5-5952a8cbc4e8.png)

**Comment by openluopworld** [comment]
和之前的逻辑类似，例如第一个原始，同样将[0e 0b 0d 09]的乘法按照比特拆分。您可以推导下。

至于为什么要这样做，主要是转化为简单的2倍乘和异或运算，2倍乘可以进一步转化为简单的左移位和异或运算。

**Comment by rpodman** [comment]
> 和之前的逻辑类似，例如第一个原始，同样将[0e 0b 0d 09]的乘法按照比特拆分。您可以推导下。
> 
> 至于为什么要这样做，主要是转化为简单的2倍乘和异或运算，2倍乘可以进一步转化为简单的左移位和异或运算。

好的, 感谢您, 差不多明白了
